feature/implement-autogeneration-django-apps
dhvcc/cookiecutter-django pull request #2
Opened 2023-11-19 19:34 UTC by Pr1ncee

## Description

I've implemented a new setting for generating Django apps. Moreover it adds a new apps to the `INSTALLED_APPS` setting and updates `urls.py` file.

Checklist:

- [+] I've made sure that tests are updated accordingly (especially if adding or updating a template option)
- [+] I've updated the documentation or confirm that my change doesn't require any updates

## Rationale

It's often not handy at all generating apps in django and even manually creating `urls.py` file in the new apps. My code make it simpler to generate a basic app with all files you need with only one row.

2023-11-20 12:28 UTC, dhvcc commented on hooks/post_gen_project.py
> +PROJECT_NAME = "{{cookiecutter.project_slug}}"
slug

2023-11-20 12:28 UTC, dhvcc commented on {{cookiecutter.project_slug}}/config/urls.py
> +urlpatterns += [path("api/v1/", include(f"{app_name}.urls")) for app_name in "{{ cookiecutter.apps }}".split(" ")]
check use_drf="n"

2023-11-20 12:28 UTC, dhvcc commented on {{cookiecutter.project_slug}}/config/settings/base.py
> +INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS + AUTOGENERATED_APPS
плюсуй в LOCAL_APPS

2023-11-20 12:28 UTC, dhvcc commented on {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/urls_template
> +router = routers.DefaultRouter()
if settings.DEBUG:
    router = DefaultRouter()
else:
    router = SimpleRouter()

2023-11-20 12:28 UTC, dhvcc commented on {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/urls_template
> +urlpatterns = [
delete

2023-11-20 12:28 UTC, dhvcc commented on cookiecutter.json
> +  "apps": "app1 app2"
chcek named arguments, may be we can provide more info in interactive mode

2023-11-22 12:06 UTC, dhvcc requested changes
Не хватает шаблонов для миграций и файла для апи, который будет использовать роутер. Насколько я понимаю тут только 2 файла , это маловато

2023-11-22 12:06 UTC, dhvcc commented on {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/apps_template
> +from django.apps import AppConfig
Положи все в отдельную папку, где названием будет переменная из jinja, как с самим проектом сделано

2023-11-22 12:06 UTC, dhvcc commented on {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/urls_template
> +urlpatterns = [
Не вижу фиксс

2023-11-22 12:06 UTC, dhvcc commented on hooks/post_gen_project.py
> +DJANGO_APP_FILES = (
Добавь комментарий зачем эта переменная

2023-11-22 12:06 UTC, dhvcc commented on hooks/post_gen_project.py
> +        files_ta_create = (
Очепятка

2023-11-22 12:06 UTC, dhvcc commented on hooks/post_gen_project.py
> +    In the example above string literals represent files and nested dicts represent directories.
In the above example, вроде бы так пишется

2023-11-22 12:06 UTC, dhvcc commented on hooks/post_gen_project.py
> +    This function supports recursive files creation in the format of:
Recursive **file** creation

2023-11-22 12:06 UTC, dhvcc commented on hooks/post_gen_project.py
> +                    with open(os.path.join(target_dir, object_name), "x") as f:
Код выглядит запутано, нужно упростить

2023-11-22 12:38 UTC, Pr1ncee commented on hooks/post_gen_project.py
> +    This function supports recursive files creation in the format of:
так мы же не файл рекурсивно создаем, а файлЫ в директории

2023-11-23 11:46 UTC, dhvcc commented on hooks/post_gen_project.py
> +    This function supports recursive files creation in the format of:
Просто пишется вроде file creation даже в plural, хот я в правилах не разбираюсь особо)))

2023-11-24 12:11 UTC, dhvcc approved these changes

2023-11-24 12:11 UTC, merged