feature/fix-forms-when-use-allauth-n
dhvcc/cookiecutter-django pull request #4
Opened 2023-11-21 13:41 UTC by Oleg11713

Allauth can be set with any flag. However, the use of UI is only possible if use_allauth == 'y'

Checklist:

- [+] I've added check for using UI with allauth
- [+] I've returned the logic for working with allauth from the admin panel

2023-11-21 15:35 UTC, Pr1ncee approved these changes

2023-11-22 11:59 UTC, dhvcc commented on hooks/pre_gen_project.py
> +    print("You should either enable allauth to use the UI or " "Start with the UI disabled.")
А что твт со строкой?

2023-11-22 12:00 UTC, dhvcc requested changes
Нужно ещё раскомментить использован е адаптера

2023-11-22 12:45 UTC, Oleg11713 commented on hooks/pre_gen_project.py
> +    print("You should either enable allauth to use the UI or " "Start with the UI disabled.")
писал по аналогии с предыдущими двумя сообщениями, хотя в целом это не имеет смысла

2023-11-22 13:23 UTC, Oleg11713 commented
> Нужно ещё раскомментить использован е адаптера

Не вижу больше ничего закомменченого, можешь сказать какой файл? Все что я заметил с чем связанно allauth, все раскоменченно, протестил, у меня все работает

2023-11-23 21:28 UTC, dhvcc commented
> > Нужно ещё раскомментить использован е адаптера
> 
> Не вижу больше ничего закомменченого, можешь сказать какой файл? Все что я заметил с чем связанно allauth, все раскоменченно, протестил, у меня все работает

Блин, а вроде и правда. Я помню что-то такое комментил, но может уже поправил

2023-11-23 21:28 UTC, dhvcc approved these changes

2023-11-23 21:29 UTC, merged